[package]
name = "flic"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.5.31" ,features = ["derive"]}
console = "0.15.11"
regex = "1.11.1"
