[package]
name = "flic"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3.12" ,features = ["derive"]}
console = "0.15.7"
regex = "1.9.1"
